spring:
  application:
    name: ride-management-service
  datasource:
    url: ${RIDE_DB_URL:jdbc:postgresql://localhost:5432/ride_db}
    username: ${RIDE_DB_USERNAME:postgres}
    password: ${RIDE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${RIDE_PORT:8083}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
