spring:
  application:
    name: fare-payment-service
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${PAYMENT_DB_USERNAME:postgres}
    password: ${PAYMENT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${PAYMENT_PORT:8084}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
